name: Deploy to S3
on:
  push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: yarn install

      - name: Run eslint
        run: yarn lint

      - name: Build
        env:
          VITE_SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          VITE_SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        run: yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        run: aws s3 cp --region ap-northeast-3 dist s3://to-do-with
